version: "3.8"

services:
  ubuntu-container:
    build: .
    container_name: ubuntu-container
    privileged: true
    volumes:
      - ./scripts:/home/scripts  
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /home/scripts
    stdin_open: true  
    tty: true         # interactive sh
    entrypoint: ["/bin/sh"]
    ports:
      - "80:80" 
    #entrypoint: /home/scripts/executable.sh

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: django
      MYSQL_PASSWORD: django
    ports:
      - "3306:3306"
    restart: always
    networks:
      - django-network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  django-network:
    driver: bridge

volumes:
  mysql-data: